### ISSUE TITLE
missing module

### ISSUE THREAD

**Issue by freekang** [leejaehoon2016/LORD#1]
python main.py --ds_name BIDMC32HR --D1 2 --D2 3 --P 100 --gpu 0
Traceback (most recent call last):
  File "/myshare/engvideo/ml/trade/liuren/ml/LORD/lord/main.py", line 2, in <module>
    from train import Main_Module
  File "/myshare/engvideo/ml/trade/liuren/ml/LORD/lord/train.py", line 4, in <module>
    from util.data_main_util import get_Data
  File "/myshare/engvideo/ml/trade/liuren/ml/LORD/lord/../util/data_main_util.py", line 9, in <module>
    from .utils.get_data import train_test_val_split, original_idx_split
  File "/myshare/engvideo/ml/trade/liuren/ml/LORD/lord/../util/utils/get_data.py", line 11, in <module>
    from ..data.functions import torch_ffill
ModuleNotFoundError: No module named 'util.data'

**Comment by leejaehoon2016** [comment]
Oh I'm sorry. I omitted this file because of .gitignore. Thank you for notifying me.
I uploaded the file.
